create or replace PACKAGE PKG_BOOKING IS

CV_BK_BKD_STAT CONSTANT BK_RQSTS.STAT%TYPE := 'BKD';
CV_BK_VOID_STAT CONSTANT BK_RQSTS.STAT%TYPE := 'VOID BKD';
CV_BK_VOID_RQST_STAT CONSTANT BK_RQSTS.STAT%TYPE := 'VBKD RQST';
CV_DLT_REJ_STAT CONSTANT BK_DLT_RQSTS.STAT%TYPE := 'DTREJ';
CV_DLT_PEND_STAT CONSTANT BK_DLT_RQSTS.STAT%TYPE := 'DTPEND';
CV_DLT_VOID_STAT CONSTANT BK_DLT_RQSTS.STAT%TYPE := 'VOID DTB';
CV_DLT_VOID_RQST_STAT CONSTANT BK_DLT_RQSTS.STAT%TYPE := 'VDTB RQST';
CV_DLT_GUAR_STAT CONSTANT BK_DLT_RQSTS.STAT%TYPE := 'DTGUAR';
CV_RQST_STATUS_REJ CONSTANT WEB_BK_REQUESTS.RQST_STATUS%TYPE := 'REJ';
CV_RQST_STATUS_APPRV CONSTANT WEB_BK_REQUESTS.RQST_STATUS%TYPE := 'APPRV';
CV_TRANS_STAT_FALSE CONSTANT WEB_BK_REQUESTS.TRANS_STAT%TYPE := 'FALSE';
CV_RQST_STATUS_PEND CONSTANT WEB_BK_REQUESTS.RQST_STATUS%TYPE := 'PEND';
CV_TRANS_STAT_TRUE CONSTANT WEB_BK_REQUESTS.TRANS_STAT%TYPE := 'TRUE';
CV_CHGD_CD CONSTANT WEB_BK_PROCS.TYP%TYPE := 'CHGD';
CV_SUBS_CD CONSTANT WEB_BK_PROCS.TYP%TYPE := 'SUBS';
CV_SWAP_CD CONSTANT WEB_BK_PROCS.TYP%TYPE := 'SWAP';
CV_SUBS_RMK CONSTANT VARCHAR2(12) := SF_GET_REF_MEANING(PKG_BOOKING.CV_SUBS_CD,'BOOKING PROCESS');

TYPE TR_BK_RQSTS IS RECORD
 (SEQ BK_RQSTS.SEQ%TYPE
 ,STAT BK_RQSTS.STAT%TYPE
 ,BS_SEQ BILL_SETS.SEQ%TYPE
 ,RQST_DATE BK_RQSTS.RQST_DATE%TYPE
 ,RQST_BK_DATE BK_RQSTS.RQST_BK_DATE%TYPE
 ,STAT_RMK BK_RQSTS.STAT_RMK%TYPE
 ,BD_SEQ BK_RQSTS.BD_SEQ%TYPE
 ,BR_SEQ_SWAP_FROM BK_RQSTS.BR_SEQ_SWAP_FROM%TYPE
 ,BS_SEQ_SWAP BK_RQSTS.BS_SEQ_SWAP%TYPE
 ,FIX_AMT BK_RQSTS.FIX_AMT%TYPE
 ,BSPS_SEQ BK_RQSTS.BSPS_SEQ%TYPE
);
TYPE TR_WEB_BK_REQUESTS IS RECORD
 (SEQ WEB_BK_REQUESTS.SEQ%TYPE
 ,VISIT_SEQ WEB_BK_REQUESTS.VISIT_SEQ%TYPE
 ,SHIP_NO WEB_BK_REQUESTS.SHIP_NO%TYPE
 ,VTY_CD WEB_BK_REQUESTS.VTY_CD%TYPE
 ,CUST_CD WEB_BK_REQUESTS.CUST_CD%TYPE
 ,INT_MOV_SEQ WEB_BK_REQUESTS.INT_MOV_SEQ%TYPE
 ,TRN_DIR WEB_BK_REQUESTS.TRN_DIR%TYPE
 ,TRN_BR_DATE WEB_BK_REQUESTS.TRN_BR_DATE%TYPE
 ,TRN_BR_RQST_DATE WEB_BK_REQUESTS.TRN_BR_RQST_DATE%TYPE
 ,ORG_BK_DATE WEB_BK_REQUESTS.ORG_BK_DATE%TYPE
 ,ORG_BK_ID WEB_BK_REQUESTS.ORG_BK_ID%TYPE
 ,PRIMARY_REF WEB_BK_REQUESTS.PRIMARY_REF%TYPE
 ,SEC_REF WEB_BK_REQUESTS.SEC_REF%TYPE
 ,AGENT WEB_BK_REQUESTS.AGENT%TYPE
 ,FIX_AMT WEB_BK_REQUESTS.FIX_AMT%TYPE
 ,NEW_EXTM_BEAM WEB_BK_REQUESTS.NEW_EXTM_BEAM%TYPE
 ,DTU_INT WEB_BK_REQUESTS.DTU_INT%TYPE
);
TYPE TR_WEB_BK_RQST_TRANS IS RECORD
 (SEQ WEB_BK_RQST_TRANS.SEQ%TYPE
 ,VISIT_SEQ WEB_BK_RQST_TRANS.VISIT_SEQ%TYPE
 ,SHIP_NO WEB_BK_RQST_TRANS.SHIP_NO%TYPE
 ,BR_SEQ WEB_BK_RQST_TRANS.BR_SEQ%TYPE
 ,CUST_CD WEB_BK_RQST_TRANS.CUST_CD%TYPE
 ,TRN_DIR WEB_BK_RQST_TRANS.TRN_DIR%TYPE
 ,BR_CANCL_DATE WEB_BK_RQST_TRANS.BR_CANCL_DATE%TYPE
 ,TRN_BR_DATE WEB_BK_RQST_TRANS.TRN_BR_DATE%TYPE
 ,RQST_STATUS WEB_BK_RQST_TRANS.RQST_STATUS%TYPE
);

PROCEDURE P_PROCESS_BOOKING
 (P_VSL_TYPE IN SHIP_ID_NO.VTY_CD%TYPE
 ,P_CSN_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_BS_SEQ IN BK_RQSTS.BS_SEQ%TYPE
 ,P_ITI_SEQ IN ITIN_ITEMS.SEQ%TYPE
 ,P_CUST_CD IN CONTACTS.SHORT_NAME%TYPE
 ,P_REAL_CUST_CD IN CONTACTS.SHORT_NAME%TYPE
 ,P_DATE_CREATED IN BK_RQSTS.RQST_DATE%TYPE
 ,P_BK_DATE IN BK_RQSTS.RQST_BK_DATE%TYPE
 ,P_TRN_DIR IN ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_ITI_TRN_DIR IN ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_EXTM_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_HML IN CUST_VSL_CHARS.LVC_HML_QUALIFIED%TYPE
 ,P_REST IN REST_USR_CDS.CD%TYPE
 ,P_GAS_FREE_IND IN VARCHAR2
 ,P_PDE_CD IN ITIN_ITEMS.PDE_CD%TYPE
 ,P_DTU_INT IN WEB_BK_REQUESTS.DTU_INT%TYPE
 ,P_AGENT IN CONTACTS.SHORT_NAME%TYPE
 ,P_DTU_SEQ IN ITIN_ITEMS.DTU_GROUP_BY_SEQ%TYPE
 ,P_TUG_NO IN SHIP_ID_NO.SHIP_NO%TYPE
 ,P_BARGE_NO IN SHIP_ID_NO.SHIP_NO%TYPE
 ,P_BR_SEQ OUT BK_RQSTS.SEQ%TYPE
 ,P_BK_STAT OUT BK_RQSTS.STAT%TYPE
 ,P_BK_COND OUT BK_CONDS.LEV%TYPE
 ,P_ERROR_CODE OUT VARCHAR2
 ,P_SUCCESS OUT VARCHAR2
 ,P_NO_FRFT_CD IN BK_RQSTS.NO_FRFT_CD%TYPE := NULL
 ,P_LOA IN CUST_VSL_CHARS.LEN_OVERALL%TYPE := NULL
 ,P_SPEC_BOOK_IND IN VARCHAR2 := NULL
 ,P_AMOUNT IN BK_RQST_DETS.AMOUNT%TYPE := NULL
 );
PROCEDURE P_PROCESS_BK_BEF_V1
 (P_VSL_TYPE IN SHIP_ID_NO.VTY_CD%TYPE
 ,P_CSN_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_BS_SEQ IN BK_RQSTS.BS_SEQ%TYPE
 ,P_ITI_SEQ IN ITIN_ITEMS.SEQ%TYPE
 ,P_CUST_CD IN CONTACTS.SHORT_NAME%TYPE
 ,P_REAL_CUST_CD IN CONTACTS.SHORT_NAME%TYPE
 ,P_DATE_CREATED IN BK_RQSTS.RQST_DATE%TYPE
 ,P_BK_DATE IN BK_RQSTS.RQST_BK_DATE%TYPE
 ,P_TRN_DIR IN ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_ITI_TRN_DIR IN ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_EXTM_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_HML IN CUST_VSL_CHARS.LVC_HML_QUALIFIED%TYPE
 ,P_REST IN REST_USR_CDS.CD%TYPE
 ,P_GAS_FREE_IND IN VARCHAR2
 ,P_PDE_CD IN ITIN_ITEMS.PDE_CD%TYPE
 ,P_DTU_INT IN WEB_BK_REQUESTS.DTU_INT%TYPE
 ,P_AGENT IN CONTACTS.SHORT_NAME%TYPE
 ,P_DTU_SEQ IN ITIN_ITEMS.DTU_GROUP_BY_SEQ%TYPE
 ,P_TUG_NO IN SHIP_ID_NO.SHIP_NO%TYPE
 ,P_BARGE_NO IN SHIP_ID_NO.SHIP_NO%TYPE
 ,P_BR_SEQ OUT BK_RQSTS.SEQ%TYPE
 ,P_BK_STAT OUT BK_RQSTS.STAT%TYPE
 ,P_BK_COND OUT BK_CONDS.LEV%TYPE
 ,P_ERROR_CODE OUT VARCHAR2
 ,P_SUCCESS OUT VARCHAR2
 ,P_NO_FRFT_CD IN BK_RQSTS.NO_FRFT_CD%TYPE := NULL
 ,P_LOA IN CUST_VSL_CHARS.LEN_OVERALL%TYPE := NULL
 ,P_SPEC_BOOK_IND IN VARCHAR2 := NULL
 ,P_AMOUNT IN BK_RQSTS.FIX_AMT%TYPE := NULL
 );
/* Calculate booking fee, period, arrival time for booking requests */
PROCEDURE P_RTV_BOOK_FEE
 (P_BS_SEQ IN BK_RQSTS.BS_SEQ%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_EXTM_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_HML IN CUST_VSL_CHARS.LVC_HML_QUALIFIED%TYPE
 ,P_REST IN REST_USR_CDS.CD%TYPE
 ,P_BK_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_BK_PERIOD OUT BK_RQSTS.BP_ID%TYPE
 ,P_SLOT_AVAIL OUT NUMBER
 ,P_ARR_TIME OUT VARCHAR2
 ,P_REJ_REASON OUT BK_RQSTS.STAT_RMK%TYPE
 );
PROCEDURE P_CANCEL_BOOK
 (P_BK_SEQ IN WEB_BK_RQST_TRANS.SEQ%TYPE
 ,P_BK_STATUS IN WEB_BK_RQST_TRANS.RQST_STATUS%TYPE
 ,P_DATE_CREATED IN DATE
 ,P_BR_SEQ IN BK_RQSTS.BR_SEQ_REBK%TYPE
 ,P_BS_SEQ IN BK_RQSTS.BS_SEQ%TYPE
 ,P_EXTM_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_HML IN CUST_VSL_CHARS.PERM_HL_IND%TYPE
 ,P_REST IN REST_USR_CDS.CD%TYPE
 ,P_TEMP_STATUS OUT BK_RQSTS.STAT%TYPE
 ,P_ERROR OUT VARCHAR2
 ,P_SUCCESS OUT VARCHAR2
 );
/* Retrieve cancellation fees for booking cancellation */
PROCEDURE P_RTV_CAN_FEE
 (P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_DATE_CREATED IN DATE
 ,P_EXTM_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_HML IN CUST_VSL_CHARS.LVC_HML_QUALIFIED%TYPE
 ,P_REST IN REST_USR_CDS.CD%TYPE
 ,P_CAN_DAYS OUT NUMBER
 ,P_CAN_HOURS OUT NUMBER
 ,P_CAN_FEE OUT NUMBER
 ,P_DAYLIGHT_TRN_CAN_FEE OUT NUMBER
 );
PROCEDURE P_CALC_CANCEL_FEE
 (P_BR_SEQ IN BK_RQSTS.BR_SEQ_REBK%TYPE
 ,P_CAN_FEE OUT NUMBER
 );
PROCEDURE P_RTV_PC_UMS
 (P_CSN_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_TRN_BR_DATE IN DATE
 ,P_PC_UMS_NET OUT NUMBER
 );
/* Insert declared hazardous cargo items */
PROCEDURE P_INS_MJR_HAZ_CGO
 (P_CSN_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_HCA_SEQ IN HAZ_CLASS_ASSIGS.SEQ%TYPE
 ,P_HCUC_UN_NO IN HAZ_COMMD_UN_CLASS.UN_NO%TYPE
 ,P_HCID_CLASS_NO IN HAZ_COMMD_IMO_CLASS.CLASS%TYPE
 ,P_HCID_DIV_NO IN HAZ_COMMD_IMO_DIV.DIV_NO%TYPE
 ,P_PROPER_SHIPNAME IN HAZ_CLASS_ASSIGS.PROPR_SHIPPG_NAME%TYPE
 ,P_METRIC_TONS IN HAZ_CGO_ITEMS.METRIC_TONS%TYPE
 ,P_STRGE_TYP IN HAZ_CGO_ITEMS.STRGE_TYP%TYPE
 ,P_AD_SEQ IN ACTVT_DETS.SEQ%TYPE
 ,P_CVD_SEQ IN CUST_VISIT_DETS.SEQ%TYPE
 ,P_HCTN_SEQ IN HAZ_COMMD_TRADE_NAMES.SEQ%TYPE
 ,P_HCCC_CD IN HAZ_COMMD_CHRIS_CLASS.CD%TYPE
 ,P_PSN_SEQ IN PCC_ITEM_SCHED_NEEDS.SEQ%TYPE
 ,P_RMK IN HAZ_CGO_ITEMS.RMK%TYPE
 );
/* Insert declared hazardous cargo items */
PROCEDURE P_INS_LAST_HAZ_CGO
 (P_CSN_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_HCA_SEQ IN HAZ_CLASS_ASSIGS.SEQ%TYPE
 ,P_HCUC_UN_NO IN HAZ_COMMD_UN_CLASS.UN_NO%TYPE
 ,P_HCID_CLASS_NO IN HAZ_COMMD_IMO_CLASS.CLASS%TYPE
 ,P_HCID_DIV_NO IN HAZ_COMMD_IMO_DIV.DIV_NO%TYPE
 ,P_PROPER_SHIPNAME IN HAZ_CLASS_ASSIGS.PROPR_SHIPPG_NAME%TYPE
 ,P_METRIC_TONS IN HAZ_CGO_ITEMS.METRIC_TONS%TYPE
 ,P_STRGE_TYP IN HAZ_CGO_ITEMS.STRGE_TYP%TYPE
 ,P_PSN_SEQ IN PCC_ITEM_SCHED_NEEDS.SEQ%TYPE
 ,P_GAS_FREE_IND IN CUST_VISIT_DETS.TBLC_GAS_FREE_IND%TYPE
 ,P_AD_SEQ IN ACTVT_DETS.SEQ%TYPE
 ,P_HCTN_SEQ IN HAZ_COMMD_TRADE_NAMES.SEQ%TYPE
 ,P_HCCC_CD IN HAZ_COMMD_CHRIS_CLASS.CD%TYPE
 ,P_RMK IN HAZ_CGO_ITEMS.RMK%TYPE
 );
PROCEDURE P_UPD_BOOK_RQSTS
 (P_WBR_SEQ IN NUMBER
 ,P_BR_SEQ IN NUMBER
 ,P_REG_BK_FEE IN NUMBER
 ,P_BK_PERS IN NUMBER
 ,P_PC_UMS_NET IN NUMBER
 ,P_REST IN REST_USR_CDS.CD%TYPE
 ,P_HML IN CUST_VSL_CHARS.LVC_HML_QUALIFIED%TYPE
 ,P_Y_JOB_RMK IN VARCHAR2
 ,P_REQ_ARR_TIME IN VARCHAR2
 ,P_REASON_FOR_REJ IN VARCHAR2
 ,P_RQST_STATUS IN VARCHAR2
 ,P_STAT_DATE IN DATE
 ,P_TRANS_STAT IN VARCHAR2
 ,P_BK_COND IN BK_CONDS.LEV%TYPE
 ,P_ACP_REP_APP IN WEB_BK_REQUESTS.ACP_REP_APP_OFF%TYPE
 ,P_SUCCESS OUT VARCHAR2
 );
PROCEDURE P_UPD_BOOK_TRANS
 (P_WBT_SEQ IN NUMBER
 ,P_BR_SEQ IN NUMBER
 ,P_BR_CANCL_DAY IN NUMBER
 ,P_BR_CANCL_HR IN NUMBER
 ,P_BR_CANCL_FEE IN NUMBER
 ,P_REASON_FOR_REJ IN VARCHAR2
 ,P_DAYLIGHT_TRN_CAN_FEE IN NUMBER
 ,P_RQST_STATUS IN VARCHAR2
 ,P_STAT_DATE IN DATE
 ,P_TRANS_STAT IN VARCHAR2
 ,P_ACP_REP_APP IN WEB_BK_REQUESTS.ACP_REP_APP_OFF%TYPE
 ,P_SUCCESS OUT VARCHAR2
 );
/* Accesar la cantidad de slots de booking disponibles */
FUNCTION F_COUNT_SLOT_AVAIL
 (P_DATE_FROM IN BK_DAYS.DATE_FROM%TYPE
 ,P_CLASS IN VARCHAR2
 ,P_BK_TYP IN BK_RQSTS.TYP%TYPE
 ,P_RQST_DATE IN BK_RQSTS.RQST_DATE%TYPE
 ,P_EVAL_PREV_DATE IN VARCHAR2 := 'Y'
 )
 RETURN NUMBER;
FUNCTION F_GET_BK_FEE
 (P_BS_SEQ IN BK_RQSTS.BS_SEQ%TYPE
 )
 RETURN NUMBER;
/* Get the arrival time parameter */
FUNCTION F_GET_ARR_PAR
 (P_BS_SEQ IN BK_RQSTS.BS_SEQ%TYPE
 ,P_EXTM_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_HML IN CUST_VSL_CHARS.PERM_HL_IND%TYPE
 ,P_REST IN REST_USR_CDS.CD%TYPE
 )
 RETURN VARCHAR2;
/* Retrieve the agent sequence */
FUNCTION F_FIND_AGENT_SEQ
 (P_AGENT IN CONTACTS.SHORT_NAME%TYPE
 )
 RETURN INTEGER;
PROCEDURE P_SAME_DAY_TRN
 (P_VISIT_SEQ IN WEB_BK_RQST_TRANS.VISIT_SEQ%TYPE
 ,P_SHIP_NO IN WEB_BK_RQST_TRANS.SHIP_NO%TYPE
 ,P_SHIP_NAME IN WEB_BK_RQST_TRANS.SHIP_NAME%TYPE
 ,P_AGENT IN WEB_BK_RQST_TRANS.AGENT%TYPE
 ,P_REASON_FOR_REJ IN WEB_BK_RQST_TRANS.REASON_FOR_REJ%TYPE
 ,P_BR_SEQ IN WEB_BK_RQST_TRANS.BR_SEQ%TYPE
 ,P_TRN_DIR IN WEB_BK_RQST_TRANS.TRN_DIR%TYPE
 ,P_ACP_REP_APP_OFF IN WEB_BK_RQST_TRANS.ACP_REP_APP_OFF%TYPE
 ,P_OPTION_RQST IN WEB_BK_RQST_TRANS.OPTION_RQST%TYPE
 ,P_BR_CANCL_DATE IN WEB_BK_RQST_TRANS.BR_CANCL_DATE%TYPE
 ,P_BR_RET_DATE IN WEB_BK_RQST_TRANS.BR_RET_DATE%TYPE
 ,P_BR_CANCL_DY IN WEB_BK_RQST_TRANS.BR_CANCL_DY%TYPE
 ,P_BR_CANCL_HR IN WEB_BK_RQST_TRANS.BR_CANCL_HR%TYPE
 ,P_BR_CANCL_FEE IN WEB_BK_RQST_TRANS.BR_CANCL_FEE%TYPE
 ,P_AGT_NAME IN WEB_BK_RQST_TRANS.AGT_NAME%TYPE
 ,P_TRN_BR_DATE IN WEB_BK_RQST_TRANS.TRN_BR_DATE%TYPE
 ,P_BK_DAYLIGHT_DATE IN WEB_BK_RQST_TRANS.BK_DAYLIGHT_DATE%TYPE
 ,P_BK_DAYLIGHT_CANCL_DATE IN WEB_BK_RQST_TRANS.BK_DAYLIGHT_CANCL_DATE%TYPE
 ,P_DAYLIGHT_CANCL_FEE IN WEB_BK_RQST_TRANS.DAYLIGHT_TRN_CANCL_FEE%TYPE
 ,P_RQST_STATUS IN WEB_BK_RQST_TRANS.RQST_STATUS%TYPE
 ,P_STAT_DATE IN WEB_BK_RQST_TRANS.STAT_DATE%TYPE
 ,P_TRANS_STAT IN WEB_BK_RQST_TRANS.TRANS_STAT%TYPE
 ,P_SUCCESS OUT VARCHAR2
 );
PROCEDURE P_UPD_SAME_DAY_TRN
 (P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_PENALTY_IND IN BK_RQSTS.PENALTY_IND%TYPE
 ,P_SUCCESS OUT VARCHAR2
 );
/* Process daylight transit requests */
PROCEDURE P_DAY_BOOKING
 (P_CSN_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_BR_SEQ IN BK_DLT_RQSTS.BR_SEQ%TYPE
 ,P_SHIP_NO IN SHIP_ID_NO.SHIP_NO%TYPE
 ,P_DT_RQST_DATE IN DATE
 ,P_EXTM_BEAM IN CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_HML IN CUST_VSL_CHARS.LVC_HML_QUALIFIED%TYPE
 ,P_REST IN REST_USR_CDS.CD%TYPE
 ,P_TRN_DIR IN ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_HL_IND IN CUST_VSL_CHARS.PERM_HL_IND%TYPE
 ,P_AGENT IN CONTACTS.SHORT_NAME%TYPE
 ,P_DR_SEQ OUT BK_DLT_RQSTS.SEQ%TYPE
 ,P_DB_STAT OUT BK_DLT_RQSTS.STAT%TYPE
 ,P_ERROR_CODE OUT VARCHAR2
 ,P_SUCCESS OUT VARCHAR2
 );
PROCEDURE P_GUAR_DAY_BOOK
 (P_DAY_SEQ IN BK_DLT_RQSTS.SEQ%TYPE
 ,P_BR_SEQ IN BK_DLT_RQSTS.BR_SEQ%TYPE
 ,P_TEMP_STATUS OUT VARCHAR2
 ,P_ERROR_CODE OUT VARCHAR2
 ,P_SUCCESS OUT VARCHAR2
 );
PROCEDURE P_DAY_CAN_BOOK
 (P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_DLT_STATUS IN BK_DLT_RQSTS.STAT%TYPE
 ,P_DLT_CAN_DATE IN DATE
 ,P_DAY_SEQ OUT BK_DLT_RQSTS.SEQ%TYPE
 ,P_TEMP_STATUS OUT BK_RQSTS.STAT%TYPE
 ,P_ERROR OUT VARCHAR2
 ,P_SUCCESS OUT VARCHAR2
 );
/* Calculate booking fee, period, arrival time for booking requests */
PROCEDURE P_RTV_DL_BOOK_FEE
 (P_DAY_SEQ IN BK_DLT_RQSTS.SEQ%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_RQST_BK_DATE IN BK_RQSTS.RQST_BK_DATE%TYPE
 ,P_DL_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_SLOT_AVAIL OUT NUMBER
 ,P_ARR_TIME OUT VARCHAR2
 ,P_REJ_REASON OUT BK_RQSTS.STAT_RMK%TYPE
 );
/* Retrieve cancellation fees for booking cancellation */
PROCEDURE P_RTV_DL_CAN_FEE
 (P_DAY_SEQ IN BK_DLT_RQSTS.SEQ%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_DL_CAN_DATE IN DATE
 ,P_RQST_BK_DATE IN DATE
 ,P_CAN_DAYS OUT NUMBER
 ,P_CAN_HOURS OUT NUMBER
 ,P_DAYLIGHT_TRN_CAN_FEE OUT NUMBER
 );
FUNCTION F_GET_TOLL_BASIS_INFO
 (P_BR_SEQ NUMBER
 ,P_SEPARATOR VARCHAR2 := SF_GET_PARAM_VAL(NULL, 'TBR_TBI_EVTMS_S')
 )
 RETURN VARCHAR2;
PROCEDURE P_MESSAGE_PARAM
 (P_BK_RQST_DATE IN DATE
 ,P_RQST_DATE IN DATE
 ,P_COND_LEVEL IN BK_CONDS.LEV%TYPE
 ,P_SLOT_TYP IN VARCHAR2
 ,P_BD_SEQ IN BK_DAYS.SEQ%TYPE
 ,P_DRV_HML IN VARCHAR2
 ,P_DRV_PDE_CD IN REST_USR_CDS.CD%TYPE
 ,P_TRN_DIR IN VARCHAR2
 ,P_CLASS IN BK_SIZE_TYPS.CLASS%TYPE
 ,P_MESSAGE OUT VARCHAR2
 );
/* Generate the Booking Swap, Substitution, Change Date Transactions */
PROCEDURE P_BOOK_TRANS_PROCS
 (P_WBP_SEQ IN WEB_BK_PROCS.SEQ%TYPE
 ,P_BR_SEQ_FIRST OUT BK_RQSTS.SEQ%TYPE
 ,P_BR_SEQ_SEC OUT BK_RQSTS.SEQ%TYPE
 ,P_BK_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_CAN_DY OUT WEB_BK_RQST_TRANS.BR_CANCL_DY%TYPE
 ,P_CAN_HR OUT WEB_BK_RQST_TRANS.BR_CANCL_HR%TYPE
 ,P_CAN_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_BK_TRANS_STAT OUT WEB_BK_REQUESTS.TRANS_STAT%TYPE
 ,P_BK_RQST_STAT OUT WEB_BK_REQUESTS.RQST_STATUS%TYPE
 ,P_BK_COND OUT BK_CONDS.LEV%TYPE
 ,P_ERROR_CODE OUT VARCHAR2
 ,P_ERROR_MESS OUT VARCHAR2
 );
/* Generate the booking swap transaction */
PROCEDURE P_BOOK_TRANS_SWAP
 (P_BK_WBP_SEQ IN WEB_BK_PROCS.SEQ%TYPE
 ,P_BK_WBP_TYP IN WEB_BK_PROCS.TYP%TYPE
 ,P_BR_WB_SEQ_FIRST OUT BK_RQSTS.SEQ%TYPE
 ,P_BR_WB_SEQ_SEC OUT BK_RQSTS.SEQ%TYPE
 ,P_BK_WB_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_BK_WB_STAT OUT WEB_BK_REQUESTS.TRANS_STAT%TYPE
 ,P_ERROR_CD OUT VARCHAR2
 );
/* Generate the booking substitution */
PROCEDURE P_BOOK_TRANS_SUBS
 (P_BK_WBP_SEQ IN WEB_BK_PROCS.SEQ%TYPE
 ,P_BK_WBP_TYP IN WEB_BK_PROCS.TYP%TYPE
 ,P_BK_WB_SEQ_FIRST OUT BK_RQSTS.SEQ%TYPE
 ,P_BK_WB_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_CAN_WB_DY OUT WEB_BK_RQST_TRANS.BR_CANCL_DY%TYPE
 ,P_CAN_WB_HR OUT WEB_BK_RQST_TRANS.BR_CANCL_HR%TYPE
 ,P_CAN_WB_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_BK_WB_STAT OUT WEB_BK_REQUESTS.TRANS_STAT%TYPE
 ,P_BK_COND OUT BK_CONDS.LEV%TYPE
 ,P_ERROR_CD OUT VARCHAR2
 );
/* Generate the Booking Change Date */
PROCEDURE P_BOOK_TRANS_CHGD
 (P_BK_WBP_SEQ IN WEB_BK_PROCS.SEQ%TYPE
 ,P_BK_WBP_TYP IN WEB_BK_PROCS.TYP%TYPE
 ,P_BK_WB_SEQ_FIRST OUT BK_RQSTS.SEQ%TYPE
 ,P_BK_WB_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_CAN_WB_DY OUT WEB_BK_RQST_TRANS.BR_CANCL_DY%TYPE
 ,P_CAN_WB_HR OUT WEB_BK_RQST_TRANS.BR_CANCL_HR%TYPE
 ,P_CAN_WB_FEE OUT CHARGES.CHRG_AMT%TYPE
 ,P_BK_WB_STAT OUT WEB_BK_REQUESTS.TRANS_STAT%TYPE
 ,P_BK_COND OUT BK_CONDS.LEV%TYPE
 ,P_ERROR_CD OUT VARCHAR2
 );
/* Retrieve some itinerary information need for booking swap, substitutio */
PROCEDURE P_GET_BK_ITIN_INFO
 (P_VISIT_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_ITI_SEQ IN ITIN_ITEMS.SEQ%TYPE
 ,P_BS_SEQ OUT BILL_SETS.SEQ%TYPE
 ,P_REST_CD OUT REST_USR_CDS.CD%TYPE
 ,P_TRN_DIR OUT ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_CUST_CD OUT VARCHAR2
 ,P_PDE_CD OUT ITIN_ITEMS.PDE_CD%TYPE
 );
/* Get the vessel characteristics for visit */
PROCEDURE P_GET_CSN_VSL_CHRS
 (P_SHIP_NO IN SHIP_ID_NO.SHIP_NO%TYPE
 ,P_VISIT_SEQ IN CUST_SCHED_NEEDS.SEQ%TYPE
 ,P_HML OUT CUST_VSL_CHARS.LVC_HML_QUALIFIED%TYPE
 ,P_EXTM_BEAM OUT CUST_VSL_CHARS.EXTM_BEAM%TYPE
 ,P_GAS_FREE OUT CUST_VISIT_DETS.TBLC_GAS_FREE_IND%TYPE
 );
/* Get information of some columns on BK_RQSTS table */
PROCEDURE P_GET_BK_RQST_INFO
 (P_BK_ID IN BK_RQSTS.SEQ%TYPE
 ,P_BK_RQST_REC OUT PKG_BOOKING.TR_BK_RQSTS
 );
/* Evaluate the rules for the booking transactions */
PROCEDURE P_EVAL_BK_TRAN_RULES
 (P_BK_WBP_TYP IN WEB_BK_PROCS.TYP%TYPE
 ,P_WB_BK_FROM_SHIPNO IN WEB_BK_REQUESTS.SHIP_NO%TYPE
 ,P_WB_BK_FROM_CUST_CD IN WEB_BK_REQUESTS.CUST_CD%TYPE
 ,P_WB_BK_FROM_TRN_DIR IN WEB_BK_REQUESTS.TRN_DIR%TYPE
 ,P_ITI_REST_FROM IN REST_USR_CDS.CD%TYPE
 ,P_ITI_TRN_DIR_FROM IN ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_ITI_CUST_CD_FROM IN VARCHAR2
 ,P_BK_REQ_ARR_FROM IN VARCHAR2
 ,P_BK_DATE_FROM IN BK_RQSTS.RQST_BK_DATE%TYPE
 ,P_BK_FIX_AMT_FROM IN BK_RQSTS.FIX_AMT%TYPE
 ,P_WB_BK_TO_SHIPNO IN WEB_BK_REQUESTS.SHIP_NO%TYPE
 ,P_WB_BK_TO_CUST_CD IN WEB_BK_REQUESTS.CUST_CD%TYPE
 ,P_WB_BK_TO_TRN_DIR IN WEB_BK_REQUESTS.TRN_DIR%TYPE
 ,P_ITI_REST_TO IN REST_USR_CDS.CD%TYPE
 ,P_ITI_TRN_DIR_TO IN ITIN_ITEMS.TII_TRN_DIR%TYPE
 ,P_ITI_CUST_CD_TO IN VARCHAR2
 ,P_BK_REQ_ARR_TO IN VARCHAR2
 ,P_BK_DATE_TO IN BK_RQSTS.RQST_BK_DATE%TYPE
 ,P_BK_FIX_AMT_TO IN BK_RQSTS.FIX_AMT%TYPE
 ,P_ERROR_CODE OUT VARCHAR2
 ,P_HML_REST_FROM IN VARCHAR2 := NULL
 ,P_HML_REST_TO IN VARCHAR2 := NULL
 ,P_SIZE_FROM IN VARCHAR2 := NULL
 ,P_SIZE_TO IN VARCHAR2 := NULL
 );
/* Get information about a previous swap. */
FUNCTION F_BK_FIND_SWAP
 (P_BK_SEQ IN BK_RQSTS.SEQ%TYPE
 )
 RETURN NUMBER;
/* Update Daylight Transit Bookings to VOID them. */
FUNCTION F_VOID_BK_DLT
 (P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_WBP_TYP IN WEB_BK_PROCS.TYP%TYPE
 )
 RETURN VARCHAR2;
/* Verify if exist slot for a given period,day,type */
FUNCTION F_EXIST_SLOT
 (P_PER IN BK_PERS.ID%TYPE
 ,P_BD_SEQ IN BK_RQSTS.BD_SEQ%TYPE
 ,P_SLOT_TYP IN BK_RQSTS.TYP%TYPE
 ,P_RQSTS_DATE IN DATE
 ,P_CLASS IN BK_SIZE_TYPS.CLASS%TYPE
 )
 RETURN BOOLEAN;
FUNCTION F_GET_BK_RQST_DETS
 (P_BR_SEQ BK_RQSTS.SEQ%TYPE
 ,P_TRNS_TYPE BK_RQST_DETS.TRNS_TYPE%TYPE
 ,P_INFO_IND INTEGER
 )
 RETURN NUMBER;
PROCEDURE P_PROCESS_SMALL_RQSTS_CHGS
 (P_BR_SEQ BK_RQSTS.SEQ%TYPE
 ,P_BSPS_SEQ BK_RQSTS.BSPS_SEQ%TYPE
 ,P_XPIECE_IND VARCHAR2
 ,P_LOA CUST_VSL_CHARS.LEN_OVERALL%TYPE
 ,P_REST REST_USR_CDS.CD%TYPE
 ,P_TRN_DIR ITIN_ITEMS.TII_TRN_DIR%TYPE
 );
/* Handle the processes related to booking daylight billing charges */
PROCEDURE P_BDR_BILL_CHRGS
 (P_BDR_SEQ IN BK_DLT_RQSTS.SEQ%TYPE
 ,P_BDR_STAT IN BK_DLT_RQSTS.STAT%TYPE
 ,P_BDR_STAT_DATE IN BK_DLT_RQSTS.STAT_DATE%TYPE
 ,P_BDR_STAT_RMK IN BK_DLT_RQSTS.STAT_RMK%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_BR_RQST_BK_DATE IN BK_RQSTS.RQST_BK_DATE%TYPE
 ,P_BDR_RQST_DATE IN BK_DLT_RQSTS.RQST_DATE%TYPE
 ,P_BDR_PREV_STAT IN BK_DLT_RQSTS.STAT%TYPE
 ,P_BDR_CANCL_DATE IN BK_DLT_RQSTS.RQST_CANCL_DATE%TYPE
 ,P_SBI_APPR IN VARCHAR2 := NULL
 );
/* Process the approval of OMS charges for Booking Daylight Requests */
PROCEDURE P_BDR_APPR_OMS_CHRG
 (P_SBI_SEQ IN SVC_BILL_INSTRS.SEQ%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_CHRG_TYP IN SVC_BILL_INSTRS.TYP%TYPE
 ,P_CHARGE_REC IN PKG_MB621000PR.RATE_RECORD_TYPE
 );
/* Handle the processes related to booking billing charges */
PROCEDURE P_BR_BILL_CHRGS
 (P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_BR_STAT IN BK_RQSTS.STAT%TYPE
 ,P_BR_STAT_DATE IN BK_RQSTS.STAT_DATE%TYPE
 ,P_BR_STAT_RMK IN BK_RQSTS.STAT_RMK%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_BR_PENALTY_IND IN BK_RQSTS.PENALTY_IND%TYPE
 ,P_BR_RQST_DATE IN BK_RQSTS.RQST_DATE%TYPE
 ,P_BR_BSPS_SEQ IN BK_RQSTS.BSPS_SEQ%TYPE
 ,P_SBI_APPR IN VARCHAR2 := NULL
 );
/* Process the approval of OMS charges for Booking Requests */
PROCEDURE P_BR_APPR_OMS_CHRG
 (P_SBI_SEQ IN SVC_BILL_INSTRS.SEQ%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_CHRG_TYP IN SVC_BILL_INSTRS.TYP%TYPE
 ,P_CHARGE_TAB IN PKG_MB620000PR.CHARGE_TABLE_TYPE
 );
/* Creation of OMS Service according to booking daylight information */
PROCEDURE P_BDR_BILL_PROC_SBI
 (P_BDR_SEQ IN BK_DLT_RQSTS.SEQ%TYPE
 ,P_BDR_STAT_DATE IN BK_DLT_RQSTS.STAT_DATE%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_WAIVE_IND IN SVC_BILL_INSTRS.WAIVE_IND%TYPE
 ,P_CHRG_TYP IN SVC_BILL_INSTRS.TYP%TYPE
 ,P_BK_CHRG_TYP IN SVC_BILL_INSTRS.BK_CHRG_TYP%TYPE
 ,P_SBI_APPR IN VARCHAR2 := NULL
 );
/* Creation of OMS Service according to booking information */
PROCEDURE P_BR_BILL_PROC_SBI
 (P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_BR_STAT_DATE IN BK_RQSTS.STAT_DATE%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_WAIVE_IND IN SVC_BILL_INSTRS.WAIVE_IND%TYPE
 ,P_CHRG_TYP IN SVC_BILL_INSTRS.TYP%TYPE
 ,P_BK_CHRG_TYP IN SVC_BILL_INSTRS.BK_CHRG_TYP%TYPE
 ,P_SBI_APPR IN VARCHAR2 := NULL
 );
/* Handle the processes related to OMS cancellation charges */
PROCEDURE P_BR_OMS_CANC_CHRG
 (P_BR_SEQ IN NUMBER
 ,P_BR_STAT_RMK IN VARCHAR2
 ,P_CHRG_TYP IN SVC_BILL_INSTRS.TYP%TYPE
 ,P_BK_CHRG_TYP IN SVC_BILL_INSTRS.BK_CHRG_TYP%TYPE
 ,P_VOID IN BOOLEAN
 );
/* Handle the processes related to review booking charges on toll charge */
PROCEDURE P_BR_TOLL_REV_CHRG
 (P_TCD_SEQ IN TOLL_CHRG_DETS.SEQ%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_BR_STAT_RMK IN BK_RQSTS.STAT_RMK%TYPE
 ,P_CHRG_TYP IN INTERFACED_CHRGS.CHRG_TYP%TYPE
 ,P_STEP_RESULT IN TOLL_WORK_FLOW_RULES.POSBLE_STEP_RESULT%TYPE
 );
/* Handle the processes related to review booking charges on OMS charge */
PROCEDURE P_BR_OMS_REV_CHRG
 (P_SBI_SEQ IN SVC_BILL_INSTRS.SEQ%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_BR_STAT_RMK IN BK_RQSTS.STAT_RMK%TYPE
 ,P_CHRG_TYP IN INTERFACED_CHRGS.CHRG_TYP%TYPE
 ,P_STEP_RESULT IN TOLL_WORK_FLOW_RULES.POSBLE_STEP_RESULT%TYPE
 );
/* Update the Booking Penalty Indicator due to Service Worklist Action. */
PROCEDURE P_BR_UPD_PEN_IND
 (P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_ERROR_CODE OUT VARCHAR2
 ,P_ERROR_MESS OUT VARCHAR2
 );
/* Approval of OMS Service according to booking information */
PROCEDURE P_BR_BILL_APPR_SBI
 (P_SBI_SEQ IN SVC_BILL_INSTRS.SEQ%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_CHRG_TYP IN SVC_BILL_INSTRS.TYP%TYPE
 ,P_BK_CHRG_TYP IN SVC_BILL_INSTRS.BK_CHRG_TYP%TYPE
 ,P_SBI_APPR IN VARCHAR2 := NULL
 );
/* Approval of OMS Service according to booking information */
PROCEDURE P_BDR_BILL_APPR_SBI
 (P_SBI_SEQ IN SVC_BILL_INSTRS.SEQ%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_BS_SEQ IN BILL_SETS.SEQ%TYPE
 ,P_CHRG_TYP IN SVC_BILL_INSTRS.TYP%TYPE
 ,P_BK_CHRG_TYP IN SVC_BILL_INSTRS.BK_CHRG_TYP%TYPE
 ,P_EFF_DATE IN DATE
 ,P_BR_RQST_BK_DATE IN BK_RQSTS.RQST_BK_DATE%TYPE
 ,P_BDR_RQST_DATE IN BK_DLT_RQSTS.RQST_DATE%TYPE
 ,P_BDR_RQST_CANCL_DATE IN BK_DLT_RQSTS.RQST_CANCL_DATE%TYPE
 ,P_BDR_STAT IN BK_DLT_RQSTS.STAT%TYPE
 ,P_BDR_PREV_STAT IN BK_DLT_RQSTS.STAT%TYPE
 ,P_SBI_APPR IN VARCHAR2 := NULL
 );
END PKG_BOOKING;