-- M:\APPS\Solicitudes\Tracker_5124_5274\BD\pkg_mb621000pr.pks
--
-- Generated for Oracle 9i on Thu Jun 16  10:58:54 2005 by Server Generator 6.5.93.2.10
 

PROMPT Creating Package 'PKG_MB621000PR'
CREATE OR REPLACE PACKAGE PKG_MB621000PR IS
 
TYPE rate_record_type IS RECORD
(EFF_DATE    CHARGES.SVC_DATE%TYPE,
 QTY         CHARGES.QTY%TYPE,
 UNIT        CHARGES.UOM%TYPE,
 DESCRIPTION CHARGES.DESCR%TYPE,
 RATE 	     CHARGES.RATE%TYPE,
 AMOUNT      CHARGES.CHRG_AMT%TYPE,
 ITEM_NO     CHARGES.TAR_TAR_NO%TYPE)
;

FUNCTION F_GET_BDT_CHARGE
 (P_EFF_DATE IN DATE
 ,P_RQST_BK_DATE IN DATE
 ,P_BDR_RQST_DATE IN DATE
 )
 RETURN RATE_RECORD_TYPE;
FUNCTION F_GET_CANCEL_BDT
 (P_EFF_DATE IN DATE
 ,P_RQST_BK_DATE IN DATE
 ,P_BDR_CANCL_DATE IN DATE
 ,P_BDR_RQST_DATE IN DATE
 ,P_BDR_STAT IN BK_DLT_RQSTS.STAT%TYPE
 ,P_BR_SEQ IN BK_RQSTS.SEQ%TYPE
 ,P_MODE IN VARCHAR2
 ,P_PCUMS IN NUMBER := null
 ,P_PC_GROSS IN NUMBER := null
 ,P_ON_DECK IN NUMBER := null
 ,P_GF_IND IN VARCHAR2 := 'null'
 ,P_HS_IND IN VARCHAR2 := 'null'
 ,P_BK_STAT IN VARCHAR2 := 'null'
 ,P_REQ_ARR IN VARCHAR2 := 'null'
 )
 RETURN RATE_RECORD_TYPE;
FUNCTION F_GET_CAN_PREV_STAT
 (P_SEQ IN BK_DLT_RQSTS.SEQ%TYPE
 ,P_STAT IN BK_DLT_RQSTS.STAT%TYPE
 )
 RETURN VARCHAR2;
PRAGMA RESTRICT_REFERENCES (F_GET_CAN_PREV_STAT, WNDS);
END PKG_MB621000PR;
/
SHOW ERROR
